/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sala221
 */
public class FrmDevoluciones extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductos
     */
    public FrmDevoluciones() {
        initComponents();
        setTitle("DEVOLUCIONES");
    }
    
     private void asignarFecha(){
//        SimpleDateFormat FORMATO = new SimpleDateFormat("dd/MM/yyyy");
//        Date fecha;
     try {
         SimpleDateFormat FORMATO = new SimpleDateFormat("dd/MM/yyyy");
         Date fecha;
         fecha = FORMATO.parse("01/01/1980");
         this.jDCfecha.setDate(fecha);
         jDCfecha.getDateEditor().setEnabled(false);
     } catch (ParseException ex) {
        JOptionPane.showMessageDialog(rootPane,"Fecha errada: "+ex.getMessage());
     }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDevoluciones = new javax.swing.JTable();
        jBtnVerDevo = new javax.swing.JButton();
        jBtnCrearDevo = new javax.swing.JButton();
        jBtnEliminarDevo = new javax.swing.JButton();
        jBtnAdicionarDevo = new javax.swing.JButton();
        jFtFirma = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAobser = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jDCfecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 63, -1));

        jLabel3.setText("Firma");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        jtblDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Firma", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblDevoluciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 570, 100));

        jBtnVerDevo.setText("Ver Devolucion");
        getContentPane().add(jBtnVerDevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 135, -1));

        jBtnCrearDevo.setText("Crear  Devoluciones");
        jBtnCrearDevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearDevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCrearDevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        jBtnEliminarDevo.setText("Eliminar Devoluciones");
        jBtnEliminarDevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarDevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEliminarDevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 135, -1));

        jBtnAdicionarDevo.setText("Adicionar  Devoluciones");
        jBtnAdicionarDevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarDevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdicionarDevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 135, -1));

        jFtFirma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFtFirmaKeyTyped(evt);
            }
        });
        getContentPane().add(jFtFirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 79, 300, -1));

        jLabel5.setText("Observaciiones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jTAobser.setColumns(20);
        jTAobser.setRows(5);
        jTAobser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTAobserKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTAobser);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 490, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 630, -1));
        getContentPane().add(jDCfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, -1));

        jButton1.setText("DOCUMENTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCrearDevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearDevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCrearDevoActionPerformed

    private void jFtFirmaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFtFirmaKeyTyped
        // TODO add your handling code here:
         int longitud = this.jFtFirma.getText().length() + 1;
        
        if(Character.isDigit(evt.getKeyChar()) || longitud > 45)
            evt.consume();
    }//GEN-LAST:event_jFtFirmaKeyTyped

    private void jBtnEliminarDevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarDevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarDevoActionPerformed

    private void jBtnAdicionarDevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarDevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAdicionarDevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          FrmDocumentos Devo= new FrmDocumentos();
        Devo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTAobserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAobserKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(( c < 'a' || c > 'z') && ( c < 'A' || c > 'Z')) evt.consume();
        
        String cadena = jTAobser.getText();
         if(cadena.length() >= 500)evt.consume();
    }//GEN-LAST:event_jTAobserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDevoluciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnAdicionarDevo;
    public javax.swing.JButton jBtnCrearDevo;
    public javax.swing.JButton jBtnEliminarDevo;
    public javax.swing.JButton jBtnVerDevo;
    private javax.swing.JButton jButton1;
    public com.toedter.calendar.JDateChooser jDCfecha;
    public javax.swing.JTextField jFtFirma;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextArea jTAobser;
    public javax.swing.JTable jtblDevoluciones;
    // End of variables declaration//GEN-END:variables
}
