/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sala221
 */
public class FrmDocumentos extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductos
     */
    public FrmDocumentos() {
        initComponents();
        setTitle("DOCUMENTOS");
    }

    private void asignarFecha(){
//        SimpleDateFormat FORMATO = new SimpleDateFormat("dd/MM/yyyy");
//        Date fecha;
     try {
         SimpleDateFormat FORMATO = new SimpleDateFormat("dd/MM/yyyy");
         Date fecha;
         fecha = FORMATO.parse("01/01/1980");
         this.jDCalendario.setDate(fecha);
         jDCalendario.getDateEditor().setEnabled(false);
     } catch (ParseException ex) {
        JOptionPane.showMessageDialog(rootPane,"Fecha errada: "+ex.getMessage());
     }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFtNumRadi = new javax.swing.JFormattedTextField();
        jFtUbicacion = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDocumento = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jBtnVerDocu = new javax.swing.JButton();
        jBtnCrearDocu = new javax.swing.JButton();
        jBtnEliminarDocu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBtnAdicionarDocu = new javax.swing.JButton();
        jDCalendario = new com.toedter.calendar.JDateChooser();
        jBtnDevoluciones = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAdesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero Radicado");

        jLabel2.setText("Descripcion");

        Fecha.setText("Fecha");

        jLabel4.setText("Ubicacion");

        try {
            jFtNumRadi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AA-AAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtNumRadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFtNumRadiActionPerformed(evt);
            }
        });
        jFtNumRadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFtNumRadiKeyTyped(evt);
            }
        });

        jFtUbicacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFtUbicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFtUbicacionKeyTyped(evt);
            }
        });

        jtbDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbDocumento);

        jBtnVerDocu.setText("Ver Documentos");

        jBtnCrearDocu.setText("Crear Documento");
        jBtnCrearDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearDocuActionPerformed(evt);
            }
        });

        jBtnEliminarDocu.setText("Eliminar Documentos");

        jBtnAdicionarDocu.setText("Adicionar Documento");

        jBtnDevoluciones.setText("DEVOLUCIONES");
        jBtnDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDevolucionesActionPerformed(evt);
            }
        });

        jTAdesc.setColumns(20);
        jTAdesc.setRows(5);
        jScrollPane2.setViewportView(jTAdesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFtNumRadi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jFtUbicacion))
                .addGap(69, 69, 69))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnVerDocu)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAdicionarDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jBtnCrearDocu)
                                .addGap(31, 31, 31)
                                .addComponent(jBtnEliminarDocu))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jBtnDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnAdicionarDocu, jBtnCrearDocu, jBtnEliminarDocu, jBtnVerDocu});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Fecha)
                        .addComponent(jFtNumRadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jFtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVerDocu)
                    .addComponent(jBtnAdicionarDocu)
                    .addComponent(jBtnCrearDocu)
                    .addComponent(jBtnEliminarDocu))
                .addGap(35, 35, 35)
                .addComponent(jBtnDevoluciones)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFtNumRadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFtNumRadiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFtNumRadiActionPerformed

    private void jFtNumRadiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFtNumRadiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if( c < '0' || c > '9') evt.consume();
         
         String cadena = jFtNumRadi.getText();
         if(cadena.length() >= 10)evt.consume();
    }//GEN-LAST:event_jFtNumRadiKeyTyped

    private void jFtUbicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFtUbicacionKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if(( c < 'a' || c > 'z') && ( c < 'A' || c > 'Z')) evt.consume();
        
        String cadena = jFtUbicacion.getText();
         if(cadena.length() >= 60)evt.consume();
    }//GEN-LAST:event_jFtUbicacionKeyTyped

    private void jBtnDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDevolucionesActionPerformed
        // TODO add your handling code here:
         FrmDevoluciones Docu= new FrmDevoluciones();
        Docu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnDevolucionesActionPerformed

    private void jBtnCrearDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearDocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCrearDocuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDocumentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDocumentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    public javax.swing.JButton jBtnAdicionarDocu;
    public javax.swing.JButton jBtnCrearDocu;
    private javax.swing.JButton jBtnDevoluciones;
    public javax.swing.JButton jBtnEliminarDocu;
    public javax.swing.JButton jBtnVerDocu;
    public com.toedter.calendar.JDateChooser jDCalendario;
    public javax.swing.JFormattedTextField jFtNumRadi;
    public javax.swing.JFormattedTextField jFtUbicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextArea jTAdesc;
    public javax.swing.JTable jtbDocumento;
    // End of variables declaration//GEN-END:variables
}
